"""
Growth Pulse Automation Engine
--------------------------------
Continuous lead-generation, pixel-verification, and outreach dispatch engine
designed to run on a Hugging Face Space (Gradio SDK, CPU Basic free tier).

Architecture:
  A. Multi-threaded scraper + Meta/Google pixel verifier
  B. SQLite-backed storage with local-file fallback + optional external DB hook
  C. SMTP dispatch engine with exponential backoff retry
  D. Daemon background loop decoupled from the Gradio HTTP interface,
     which stays up to receive external keep-alive pings.
"""

import os
import re
import ssl
import csv
import time
import json
import sqlite3
import logging
import smtplib
import threading
from datetime import datetime, date
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, field
from typing import Optional

import requests
import gradio as gr

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(threadName)s | %(message)s",
)
logger = logging.getLogger("growth_pulse")

# ---------------------------------------------------------------------------
# Configuration (all values sourced from environment / HF Space Secrets)
# ---------------------------------------------------------------------------

@dataclass
class Config:
    email_user: Optional[str] = field(default_factory=lambda: os.environ.get("EMAIL_USER"))
    email_pass: Optional[str] = field(default_factory=lambda: os.environ.get("EMAIL_PASS"))
    smtp_host: str = "smtp.gmail.com"
    smtp_port: int = 465
    sender_display_name: str = field(default_factory=lambda: os.environ.get("SENDER_DISPLAY_NAME", "Growth Pulse"))

    # External DB hook (optional). If DATABASE_URL is set, the storage layer
    # will attempt to use it via psycopg2 instead of local SQLite.
    database_url: Optional[str] = field(default_factory=lambda: os.environ.get("DATABASE_URL"))

    # Local persistence paths (ephemeral on HF unless a Persistent Storage
    # volume is attached and mounted at /data).
    data_dir: str = field(default_factory=lambda: os.environ.get("DATA_DIR", "/data" if os.path.isdir("/data") else "."))
    sqlite_filename: str = "growth_pulse.db"
    sent_leads_filename: str = "sent_leads.txt"

    # Input queue: a CSV file with columns "domain,contact_email" that the
    # operator populates with real scraped leads (e.g. from Google Maps
    # exports). No synthetic rows are generated by this script.
    leads_queue_path: str = field(default_factory=lambda: os.environ.get("LEADS_QUEUE_PATH", "leads_queue.csv"))

    scrape_timeout_seconds: int = 8
    scrape_max_workers: int = 6
    loop_interval_seconds: int = int(os.environ.get("LOOP_INTERVAL_SECONDS", "300"))
    max_retries: int = 3

    user_agent: str = (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    )

    @property
    def sqlite_path(self) -> str:
        return os.path.join(self.data_dir, self.sqlite_filename)

    @property
    def sent_leads_path(self) -> str:
        return os.path.join(self.data_dir, self.sent_leads_filename)


CONFIG = Config()

# ---------------------------------------------------------------------------
# Shared runtime state (thread-safe) — powers the Gradio dashboard
# ---------------------------------------------------------------------------

class EngineState:
    def __init__(self) -> None:
        self._lock = threading.Lock()
        self.status: str = "Initializing"
        self.emails_dispatched_today: int = 0
        self.leads_scraped_total: int = 0
        self.leads_with_pixel_total: int = 0
        self.errors_total: int = 0
        self.last_cycle_started_at: Optional[str] = None
        self.last_cycle_completed_at: Optional[str] = None
        self.last_error: Optional[str] = None
        self._counter_date: date = date.today()

    def _roll_daily_counter_if_needed(self) -> None:
        today = date.today()
        if today != self._counter_date:
            self.emails_dispatched_today = 0
            self._counter_date = today

    def set_status(self, status: str) -> None:
        with self._lock:
            self.status = status

    def mark_cycle_start(self) -> None:
        with self._lock:
            self.last_cycle_started_at = datetime.now().isoformat(timespec="seconds")

    def mark_cycle_complete(self) -> None:
        with self._lock:
            self.last_cycle_completed_at = datetime.now().isoformat(timespec="seconds")

    def record_lead_scraped(self, has_pixel: bool) -> None:
        with self._lock:
            self.leads_scraped_total += 1
            if has_pixel:
                self.leads_with_pixel_total += 1

    def record_email_sent(self) -> None:
        with self._lock:
            self._roll_daily_counter_if_needed()
            self.emails_dispatched_today += 1

    def record_error(self, message: str) -> None:
        with self._lock:
            self.errors_total += 1
            self.last_error = message

    def snapshot(self) -> dict:
        with self._lock:
            self._roll_daily_counter_if_needed()
            return {
                "status": self.status,
                "emails_dispatched_today": self.emails_dispatched_today,
                "leads_scraped_total": self.leads_scraped_total,
                "leads_with_pixel_total": self.leads_with_pixel_total,
                "errors_total": self.errors_total,
                "last_cycle_started_at": self.last_cycle_started_at,
                "last_cycle_completed_at": self.last_cycle_completed_at,
                "last_error": self.last_error,
            }


STATE = EngineState()

# ---------------------------------------------------------------------------
# Component B: Storage layer (SQLite primary, optional external DB hook)
# ---------------------------------------------------------------------------

class StorageBackend:
    """
    Wraps persistence. Defaults to local SQLite (ephemeral unless /data is a
    mounted persistent volume on the HF Space). If DATABASE_URL is present,
    external database writes are attempted through a dedicated adapter so the
    ephemeral local file never becomes the single source of truth in a
    production deployment.
    """

    def __init__(self, config: Config) -> None:
        self.config = config
        self._local_lock = threading.Lock()
        self._external_adapter = None
        os.makedirs(self.config.data_dir, exist_ok=True)
        self._init_sqlite()
        if self.config.database_url:
            self._init_external()

    def _init_sqlite(self) -> None:
        with self._local_lock:
            connection = sqlite3.connect(self.config.sqlite_path)
            cursor = connection.cursor()
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS leads (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    domain TEXT NOT NULL,
                    contact_email TEXT,
                    phone_number TEXT,
                    has_meta_pixel INTEGER NOT NULL DEFAULT 0,
                    has_google_ads_tag INTEGER NOT NULL DEFAULT 0,
                    scrape_status TEXT NOT NULL,
                    email_status TEXT NOT NULL DEFAULT 'not_sent',
                    scraped_at TEXT NOT NULL,
                    UNIQUE(domain)
                )
                """
            )
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS dispatch_log (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    domain TEXT NOT NULL,
                    contact_email TEXT NOT NULL,
                    sent_at TEXT NOT NULL,
                    outcome TEXT NOT NULL
                )
                """
            )
            connection.commit()
            connection.close()
        logger.info("SQLite storage initialized at %s", self.config.sqlite_path)

    def _init_external(self) -> None:
        try:
            import psycopg2  # imported lazily; only required if DATABASE_URL is set
            self._external_adapter = psycopg2
            connection = psycopg2.connect(self.config.database_url)
            cursor = connection.cursor()
            cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS leads (
                    id SERIAL PRIMARY KEY,
                    domain TEXT UNIQUE NOT NULL,
                    contact_email TEXT,
                    phone_number TEXT,
                    has_meta_pixel BOOLEAN NOT NULL DEFAULT FALSE,
                    has_google_ads_tag BOOLEAN NOT NULL DEFAULT FALSE,
                    scrape_status TEXT NOT NULL,
                    email_status TEXT NOT NULL DEFAULT 'not_sent',
                    scraped_at TIMESTAMPTZ NOT NULL
                )
                """
            )
            connection.commit()
            cursor.close()
            connection.close()
            logger.info("External database hook verified via DATABASE_URL.")
        except ModuleNotFoundError:
            logger.warning(
                "DATABASE_URL was provided but psycopg2 is not installed. "
                "Falling back to SQLite only. Install psycopg2-binary to enable it."
            )
            self._external_adapter = None
        except Exception as exc:
            logger.error("External database initialization failed: %s", exc)
            self._external_adapter = None

    def save_lead(self, domain: str, contact_email: Optional[str], phone_number: Optional[str],
                  has_meta_pixel: bool, has_google_ads_tag: bool, scrape_status: str) -> None:
        scraped_at = datetime.now().isoformat(timespec="seconds")
        with self._local_lock:
            connection = sqlite3.connect(self.config.sqlite_path)
            cursor = connection.cursor()
            cursor.execute(
                """
                INSERT INTO leads (domain, contact_email, phone_number, has_meta_pixel,
                                    has_google_ads_tag, scrape_status, scraped_at)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                ON CONFLICT(domain) DO UPDATE SET
                    contact_email=excluded.contact_email,
                    phone_number=excluded.phone_number,
                    has_meta_pixel=excluded.has_meta_pixel,
                    has_google_ads_tag=excluded.has_google_ads_tag,
                    scrape_status=excluded.scrape_status,
                    scraped_at=excluded.scraped_at
                """,
                (domain, contact_email, phone_number, int(has_meta_pixel),
                 int(has_google_ads_tag), scrape_status, scraped_at),
            )
            connection.commit()
            connection.close()

        if self._external_adapter is not None:
            try:
                connection = self._external_adapter.connect(self.config.database_url)
                cursor = connection.cursor()
                cursor.execute(
                    """
                    INSERT INTO leads (domain, contact_email, phone_number, has_meta_pixel,
                                        has_google_ads_tag, scrape_status, scraped_at)
                    VALUES (%s, %s, %s, %s, %s, %s, %s)
                    ON CONFLICT (domain) DO UPDATE SET
                        contact_email=EXCLUDED.contact_email,
                        phone_number=EXCLUDED.phone_number,
                        has_meta_pixel=EXCLUDED.has_meta_pixel,
                        has_google_ads_tag=EXCLUDED.has_google_ads_tag,
                        scrape_status=EXCLUDED.scrape_status,
                        scraped_at=EXCLUDED.scraped_at
                    """,
                    (domain, contact_email, phone_number, has_meta_pixel,
                     has_google_ads_tag, scrape_status, scraped_at),
                )
                connection.commit()
                cursor.close()
                connection.close()
            except Exception as exc:
                logger.error("External DB write failed for %s: %s", domain, exc)

    def mark_email_sent(self, domain: str, contact_email: str, outcome: str) -> None:
        sent_at = datetime.now().isoformat(timespec="seconds")
        with self._local_lock:
            connection = sqlite3.connect(self.config.sqlite_path)
            cursor = connection.cursor()
            cursor.execute(
                "UPDATE leads SET email_status = ? WHERE domain = ?",
                ("sent" if outcome == "success" else "failed", domain),
            )
            cursor.execute(
                "INSERT INTO dispatch_log (domain, contact_email, sent_at, outcome) VALUES (?, ?, ?, ?)",
                (domain, contact_email, sent_at, outcome),
            )
            connection.commit()
            connection.close()

        # Local flat-file fallback tracker, per requirement, kept in sync
        # regardless of which DB backend is active.
        with open(self.config.sent_leads_path, "a", encoding="utf-8") as handle:
            handle.write(f"{sent_at}\t{domain}\t{contact_email}\t{outcome}\n")

    def already_contacted(self, domain: str) -> bool:
        if not os.path.exists(self.config.sent_leads_path):
            return False
        with open(self.config.sent_leads_path, "r", encoding="utf-8") as handle:
            for line in handle:
                parts = line.rstrip("\n").split("\t")
                if len(parts) >= 4 and parts[1] == domain and parts[3] == "success":
                    return True
        return False


STORAGE = StorageBackend(CONFIG)

# ---------------------------------------------------------------------------
# Component A: Scraper + pixel verifier
# ---------------------------------------------------------------------------

META_PIXEL_MARKER = "connect.facebook.net/en_US/fbevents.js"
GOOGLE_ADS_TAG_MARKER = "googletagmanager.com/gtag/js"

# Matches international/US-style phone numbers, e.g. +1 (555) 123-4567,
# 555-123-4567, +234 803 123 4567, 08031234567
PHONE_REGEX = re.compile(
    r"(\+?\d{1,3}[\s.-]?)?(\(?\d{2,4}\)?[\s.-]?)\d{3,4}[\s.-]?\d{3,4}"
)


def normalize_domain(raw_domain: str) -> str:
    domain = raw_domain.strip()
    if not domain.startswith("http://") and not domain.startswith("https://"):
        domain = "https://" + domain
    return domain


def scrape_domain(raw_domain: str) -> dict:
    """
    Fetches a single domain's homepage and inspects the raw HTML for Meta
    Pixel and Google Ads Tag script source references, and extracts the
    first phone-number-shaped string found on the page.
    """
    url = normalize_domain(raw_domain)
    headers = {"User-Agent": CONFIG.user_agent}
    result = {
        "domain": raw_domain.strip(),
        "has_meta_pixel": False,
        "has_google_ads_tag": False,
        "phone_number": None,
        "status": "unknown",
    }

    try:
        response = requests.get(url, headers=headers, timeout=CONFIG.scrape_timeout_seconds)
        html_text = response.text
        result["has_meta_pixel"] = META_PIXEL_MARKER in html_text
        result["has_google_ads_tag"] = GOOGLE_ADS_TAG_MARKER in html_text

        phone_match = PHONE_REGEX.search(html_text)
        if phone_match:
            candidate = re.sub(r"\s+", " ", phone_match.group(0)).strip()
            digit_count = len(re.sub(r"\D", "", candidate))
            if 7 <= digit_count <= 15:
                result["phone_number"] = candidate

        result["status"] = "success" if response.status_code == 200 else f"http_{response.status_code}"
    except requests.exceptions.Timeout:
        result["status"] = "timeout"
    except requests.exceptions.ConnectionError:
        result["status"] = "connection_error"
    except requests.exceptions.RequestException as exc:
        result["status"] = f"request_error:{exc}"
    except Exception as exc:
        result["status"] = f"unexpected_error:{exc}"

    return result


def scrape_domains_parallel(domains: list) -> list:
    """
    Runs scrape_domain across a list of domains concurrently using a
    ThreadPoolExecutor, bounded by CONFIG.scrape_max_workers to stay within
    the CPU Basic free tier's resource envelope.
    """
    results = []
    if not domains:
        return results

    with ThreadPoolExecutor(max_workers=CONFIG.scrape_max_workers, thread_name_prefix="scraper") as executor:
        future_to_domain = {executor.submit(scrape_domain, domain): domain for domain in domains}
        for future in as_completed(future_to_domain):
            domain = future_to_domain[future]
            try:
                results.append(future.result())
            except Exception as exc:
                logger.error("Scrape task for %s raised an exception: %s", domain, exc)
                results.append({
                    "domain": domain,
                    "has_meta_pixel": False,
                    "has_google_ads_tag": False,
                    "phone_number": None,
                    "status": f"task_exception:{exc}",
                })
    return results

# ---------------------------------------------------------------------------
# Component C: SMTP dispatch engine with exponential backoff
# ---------------------------------------------------------------------------

def build_outreach_message(sender_email: str, recipient_email: str, domain: str) -> MIMEMultipart:
    message = MIMEMultipart("alternative")
    message["Subject"] = f"Quick question about {domain}'s ad tracking setup"
    message["From"] = f"{CONFIG.sender_display_name} <{sender_email}>"
    message["To"] = recipient_email

    text_body = (
        f"Hello,\n\n"
        f"I took a look at {domain} and wanted to reach out directly.\n\n"
        f"We help local service businesses turn their existing traffic into "
        f"booked jobs through tightened ad tracking and lead-generation systems.\n\n"
        f"Happy to share a short breakdown of what we found if that's useful.\n\n"
        f"Best,\n{CONFIG.sender_display_name}"
    )
    message.attach(MIMEText(text_body, "plain"))
    return message


def send_email_with_retry(recipient_email: str, domain: str) -> str:
    """
    Attempts to send an outreach email via Gmail SMTP over SSL (port 465),
    retrying up to CONFIG.max_retries times with exponential backoff
    (2^retry_count seconds) on transient failures.
    Returns "success" or "failed".
    """
    if not CONFIG.email_user or not CONFIG.email_pass:
        logger.error("EMAIL_USER / EMAIL_PASS are not set in the environment. Cannot dispatch email.")
        STATE.record_error("Missing EMAIL_USER/EMAIL_PASS environment secrets.")
        return "failed"

    message = build_outreach_message(CONFIG.email_user, recipient_email, domain)
    ssl_context = ssl.create_default_context()

    for retry_count in range(CONFIG.max_retries):
        try:
            with smtplib.SMTP_SSL(CONFIG.smtp_host, CONFIG.smtp_port, context=ssl_context, timeout=15) as server:
                server.login(CONFIG.email_user, CONFIG.email_pass)
                server.sendmail(CONFIG.email_user, recipient_email, message.as_string())
            logger.info("Email sent to %s for domain %s on attempt %d", recipient_email, domain, retry_count + 1)
            STATE.record_email_sent()
            return "success"
        except smtplib.SMTPAuthenticationError as exc:
            logger.error("SMTP authentication failed: %s", exc)
            STATE.record_error(f"SMTP auth failure: {exc}")
            return "failed"
        except (smtplib.SMTPException, OSError) as exc:
            wait_seconds = 2 ** retry_count
            logger.warning("SMTP send attempt %d/%d for %s failed (%s). Retrying in %d seconds.", retry_count + 1, CONFIG.max_retries, recipient_email, exc, wait_seconds)
            STATE.record_error(f"SMTP transient failure: {exc}")
            time.sleep(wait_seconds)

    logger.error("All %d SMTP attempts failed for %s.", CONFIG.max_retries, recipient_email)
    return "failed"

# ---------------------------------------------------------------------------
# Lead queue reader
# ---------------------------------------------------------------------------

def read_leads_queue() -> list:
    """
    Reads the operator-supplied CSV queue file. Expected columns:
    domain,contact_email
    Rows with a domain already marked as successfully contacted are skipped.
    """
    queue_path = CONFIG.leads_queue_path
    if not os.path.exists(queue_path):
        logger.warning("Leads queue file not found at %s. Nothing to process this cycle.", queue_path)
        return []

    rows = []
    with open(queue_path, "r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        for record in reader:
            domain = (record.get("domain") or "").strip()
            contact_email = (record.get("contact_email") or "").strip()
            if not domain:
                continue
            if STORAGE.already_contacted(domain):
                continue
            rows.append({"domain": domain, "contact_email": contact_email})
    return rows

# ---------------------------------------------------------------------------
# Component D: Background automation loop
# ---------------------------------------------------------------------------

def run_automation_cycle() -> None:
    STATE.mark_cycle_start()
    STATE.set_status("Scraping")

    queued_leads = read_leads_queue()
    if not queued_leads:
        STATE.set_status("Idle (queue empty)")
        STATE.mark_cycle_complete()
        return

    domains = [lead["domain"] for lead in queued_leads]
    email_by_domain = {lead["domain"]: lead["contact_email"] for lead in queued_leads}

    scrape_results = scrape_domains_parallel(domains)

    STATE.set_status("Dispatching")
    for result in scrape_results:
        domain = result["domain"]
        has_pixel = bool(result["has_meta_pixel"] or result["has_google_ads_tag"])
        STATE.record_lead_scraped(has_pixel)

        STORAGE.save_lead(
            domain=domain,
            contact_email=email_by_domain.get(domain) or None,
            phone_number=result["phone_number"],
            has_meta_pixel=result["has_meta_pixel"],
            has_google_ads_tag=result["has_google_ads_tag"],
            scrape_status=result["status"],
        )

        recipient_email = email_by_domain.get(domain)
        if recipient_email and result["status"] == "success":
            outcome = send_email_with_retry(recipient_email, domain)
            STORAGE.mark_email_sent(domain, recipient_email, outcome)

    STATE.set_status("Idle")
    STATE.mark_cycle_complete()


def automation_loop() -> None:
    logger.info("Growth Pulse background automation loop starting.")
    while True:
        try:
            run_automation_cycle()
        except Exception as exc:
            logger.exception("Unhandled exception in automation cycle: %s", exc)
            STATE.record_error(f"Unhandled cycle exception: {exc}")
            STATE.set_status("Error - retrying next cycle")
        time.sleep(CONFIG.loop_interval_seconds)


# ---------------------------------------------------------------------------
# Gradio dashboard (keeps an HTTP port open for external keep-alive pings)
# ---------------------------------------------------------------------------

def get_dashboard_metrics():
    snapshot = STATE.snapshot()
    return (
        snapshot["status"],
        snapshot["emails_dispatched_today"],
        snapshot["leads_scraped_total"],
        snapshot["leads_with_pixel_total"],
        snapshot["errors_total"],
        snapshot["last_cycle_started_at"] or "Not yet run",
        snapshot["last_cycle_completed_at"] or "Not yet run",
        snapshot["last_error"] or "None",
    )


def build_dashboard() -> gr.Blocks:
    with gr.Blocks(title="Growth Pulse Automation Engine") as dashboard:
        gr.Markdown("# Growth Pulse — Automation Engine Status")
        gr.Markdown(
            "This dashboard exposes an HTTP endpoint so external uptime monitors "
            "can keep this Space awake. The scraping and dispatch engine runs "
            "independently in a background thread."
        )

        with gr.Row():
            status_box = gr.Textbox(label="Engine Status", interactive=False)
            errors_box = gr.Number(label="Errors Total", interactive=False)

        with gr.Row():
            emails_box = gr.Number(label="Emails Dispatched Today", interactive=False)
            leads_box = gr.Number(label="Leads Scraped Total", interactive=False)
            pixel_box = gr.Number(label="Leads With Ad Pixel Detected", interactive=False)

        with gr.Row():
            started_box = gr.Textbox(label="Last Cycle Started", interactive=False)
            completed_box = gr.Textbox(label="Last Cycle Completed", interactive=False)

        last_error_box = gr.Textbox(label="Last Error", interactive=False)
        refresh_button = gr.Button("Refresh Metrics")

        outputs = [
            status_box, emails_box, leads_box, pixel_box,
            errors_box, started_box, completed_box, last_error_box,
        ]

        refresh_button.click(fn=get_dashboard_metrics, inputs=None, outputs=outputs)
        dashboard.load(fn=get_dashboard_metrics, inputs=None, outputs=outputs)

    return dashboard


# ---------------------------------------------------------------------------
# Entrypoint
# ---------------------------------------------------------------------------

def main() -> None:
    STATE.set_status("Starting")
    background_thread = threading.Thread(target=automation_loop, name="automation_loop", daemon=True)
    background_thread.start()

    app_interface = build_dashboard()
    app_interface.queue()
    app_interface.launch(server_name="0.0.0.0", server_port=int(os.environ.get("PORT", "7860")))


if __name__ == "__main__":
    main()
